### ISSUE TITLE
项目报错~

### ISSUE THREAD

**Issue by lovexiaov** [iFarSeer/TodoFluxArchitecture#1]
/Users/lovexiaov/gitrepo/TodoFluxArchitecture/app/src/main/java/com/farseer/todo/flux/action/TodoLISTAction.java
Error:(32, 8) 错误: 类TodoListAction是公共的, 应在名为 TodoListAction.java 的文件中声明
/Users/lovexiaov/gitrepo/TodoFluxArchitecture/app/src/main/java/com/farseer/todo/flux/di/component/ActivityComponent.java

这个类的文件名错啦~

**Comment by iFarSeer** [comment]
问题原因是重名TodoLISTAction.java->TodoListAction.java时，没有彻底同步到git仓库中。
谢谢你，帮助我发现这个问题。Thx~

**Comment by iFarSeer** [comment]
fix commit:
https://github.com/iFarSeer/TodoFluxArchitecture/commit/43c29330ee4385a6e7a77e429e8709fd88d1e26d
